export type Support = "yes" | "partial" | "no" | "unknown";

export type Wallet = {
  id: string;
  name: string;
  kind: "hardware" | "browser" | "mobile" | "smart-contract";
  support: Support;
  /** A short justification visible to the user. */
  notes?: string;
  /** Optional URL with more detail (release notes, issue, PR). */
  ref?: string;
  /** Path to a logo SVG under /public/wallets/, sourced from walletbeat. */
  logo: string;
  /** Brand colour, used for the logo's background tint. */
  color: string;
  /** Wallet website. */
  url?: string;
};

export const lastUpdated = "2026-05-07";

export const wallets: Wallet[] = [
  {
    id: "keycard-shell",
    name: "Keycard Shell",
    kind: "hardware",
    support: "yes",
    notes:
      "First implementation. Displays the EIP-712 digest and the calldata digest on every signing prompt.",
    ref: "https://x.com/PatrickAlphaC/status/2054358838074122350",
    logo: "/wallets/keycard-shell.svg",
    color: "#e6492c",
    url: "https://keycard.tech/",
  },
  {
    id: "metamask",
    name: "MetaMask",
    kind: "browser",
    support: "no",
    logo: "/wallets/metamask.svg",
    color: "#f6851b",
    url: "https://metamask.io/",
  },
  {
    id: "ledger",
    name: "Ledger",
    kind: "hardware",
    support: "no",
    notes: "Hardware-side display upgrades pending.",
    logo: "/wallets/ledger.svg",
    color: "#ffffff",
    url: "https://www.ledger.com/",
  },
  {
    id: "trezor",
    name: "Trezor",
    kind: "hardware",
    support: "no",
    logo: "/wallets/trezor.svg",
    color: "#ffffff",
    url: "https://trezor.io/",
  },
  {
    id: "rabby",
    name: "Rabby",
    kind: "browser",
    support: "no",
    logo: "/wallets/rabby.svg",
    color: "#7084ff",
    url: "https://rabby.io/",
  },
  {
    id: "frame",
    name: "Frame",
    kind: "browser",
    support: "no",
    logo: "/wallets/frame.svg",
    color: "#00d2c4",
    url: "https://frame.sh/",
  },
  {
    id: "phantom",
    name: "Phantom",
    kind: "browser",
    support: "no",
    logo: "/wallets/phantom.svg",
    color: "#ab9ff2",
    url: "https://phantom.app/",
  },
  {
    id: "safe",
    name: "Safe{Wallet}",
    kind: "smart-contract",
    support: "no",
    logo: "/wallets/safe.svg",
    color: "#12ff80",
    url: "https://safe.global/",
  },
  {
    id: "rainbow",
    name: "Rainbow",
    kind: "mobile",
    support: "no",
    logo: "/wallets/rainbow.svg",
    color: "#ff4f93",
    url: "https://rainbow.me/",
  },
  {
    id: "zerion",
    name: "Zerion",
    kind: "mobile",
    support: "no",
    logo: "/wallets/zerion.svg",
    color: "#2962ef",
    url: "https://zerion.io/",
  },
  {
    id: "uniswap-wallet",
    name: "Uniswap Wallet",
    kind: "mobile",
    support: "no",
    logo: "/wallets/uniswap-wallet.svg",
    color: "#ff007a",
    url: "https://wallet.uniswap.org/",
  },
  {
    id: "onekey",
    name: "OneKey",
    kind: "hardware",
    support: "no",
    logo: "/wallets/onekey.svg",
    color: "#44d62c",
    url: "https://onekey.so/",
  },
  {
    id: "keystone",
    name: "Keystone",
    kind: "hardware",
    support: "no",
    logo: "/wallets/keystone.svg",
    color: "#ffffff",
    url: "https://keyst.one/",
  },
  {
    id: "gridplus",
    name: "GridPlus Lattice1",
    kind: "hardware",
    support: "no",
    logo: "/wallets/gridplus.svg",
    color: "#5dc9b9",
    url: "https://gridplus.io/",
  },
  {
    id: "ambire",
    name: "Ambire",
    kind: "smart-contract",
    support: "no",
    logo: "/wallets/ambire.svg",
    color: "#ae60ff",
    url: "https://ambire.com/",
  },
  {
    id: "bitbox",
    name: "BitBox",
    kind: "hardware",
    support: "no",
    logo: "/wallets/bitbox.svg",
    color: "#5e94bf",
    url: "https://bitbox.swiss/",
  },
  {
    id: "cypherock",
    name: "Cypherock",
    kind: "hardware",
    support: "no",
    logo: "/wallets/cypherock.svg",
    color: "#1a73e8",
    url: "https://cypherock.com/",
  },
  {
    id: "firefly",
    name: "Firefly",
    kind: "hardware",
    support: "no",
    logo: "/wallets/firefly.svg",
    color: "#ffa500",
    url: "https://firefly.city/",
  },
  {
    id: "imkey",
    name: "imKey",
    kind: "hardware",
    support: "no",
    logo: "/wallets/imkey.svg",
    color: "#1c52ff",
    url: "https://imkey.im/",
  },
  {
    id: "ngrave",
    name: "NGRAVE",
    kind: "hardware",
    support: "no",
    logo: "/wallets/ngrave.svg",
    color: "#d4af6a",
    url: "https://www.ngrave.io/",
  },
  {
    id: "okx",
    name: "OKX Wallet",
    kind: "browser",
    support: "no",
    logo: "/wallets/okx.png",
    color: "#ffffff",
    url: "https://www.okx.com/web3",
  },
  {
    id: "nufi",
    name: "NuFi",
    kind: "browser",
    support: "no",
    logo: "/wallets/nufi.svg",
    color: "#7a5cff",
    url: "https://nu.fi/",
  },
  {
    id: "mtpelerin",
    name: "Mt Pelerin",
    kind: "browser",
    support: "no",
    logo: "/wallets/mtpelerin.svg",
    color: "#ff5a5f",
    url: "https://www.mtpelerin.com/",
  },
  {
    id: "imtoken",
    name: "imToken",
    kind: "mobile",
    support: "no",
    logo: "/wallets/imtoken.svg",
    color: "#11c4d1",
    url: "https://token.im/",
  },
  {
    id: "bitget",
    name: "Bitget Wallet",
    kind: "mobile",
    support: "no",
    logo: "/wallets/bitget.svg",
    color: "#54ffe9",
    url: "https://web3.bitget.com/",
  },
  {
    id: "base-app",
    name: "Base App",
    kind: "mobile",
    support: "no",
    logo: "/wallets/base-app.png",
    color: "#0052ff",
    url: "https://www.base.org/",
  },
  {
    id: "family",
    name: "Family",
    kind: "mobile",
    support: "no",
    logo: "/wallets/family.svg",
    color: "#000000",
    url: "https://family.co/",
  },
  {
    id: "gemwallet",
    name: "GemWallet",
    kind: "mobile",
    support: "no",
    logo: "/wallets/gemwallet.svg",
    color: "#ff5722",
    url: "https://gemwallet.com/",
  },
  {
    id: "pillarx",
    name: "PillarX",
    kind: "mobile",
    support: "no",
    logo: "/wallets/pillarx.svg",
    color: "#7551e9",
    url: "https://pillarx.app/",
  },
  {
    id: "zeus",
    name: "Zeus",
    kind: "mobile",
    support: "no",
    logo: "/wallets/zeus.svg",
    color: "#ffd400",
    url: "https://zeusln.com/",
  },
  {
    id: "daimo",
    name: "Daimo",
    kind: "smart-contract",
    support: "no",
    logo: "/wallets/daimo.svg",
    color: "#1c7eff",
    url: "https://daimo.com/",
  },
  {
    id: "elytro",
    name: "Elytro",
    kind: "smart-contract",
    support: "no",
    logo: "/wallets/elytro.svg",
    color: "#7c5cff",
    url: "https://elytro.com/",
  },
];

export const supportLabel: Record<Support, string> = {
  yes: "Implemented",
  partial: "Partial",
  no: "Not implemented",
  unknown: "Unknown",
};

export const kindLabel: Record<Wallet["kind"], string> = {
  hardware: "Hardware",
  browser: "Browser extension",
  mobile: "Mobile",
  "smart-contract": "Smart contract"
};
